### ISSUE TITLE
Make sure that documentation is beginner-friendly

### ISSUE THREAD

**Issue by ptmerz** [shirtsgroup/physical_validation#49]
Ideally, the documentation should allow users having moderate knowledge of molecular simulations to run tests on their systems within a few minutes. It should then have additional information for users interested in the details of theory or implementation. It would be very helpful if group members that have little or no knowledge of the physical validation package could verify if the current documentation is beginner-friendly, and suggest improvements!

**Comment by wehs7661** [comment]
I'm happy to get involved with this if needed!

**Comment by schwinns** [comment]
I should be able to start using it this week (like Wed. 2/3), and I'll make notes as I go.

**Comment by wehs7661** [comment]
I will run some simple tests using the package by this weekend to share my thoughts by this weekend (Feb. 7).

**Comment by schwinns** [comment]
Overall, I think the docs are pretty clear. The examples make it easy to quickly get results. I worked through all the examples and then tried it on some simple simulations. I only had a couple suggestions, and I was not sure what would be the best way to make them. (I could try a pull request, but I don't know how to make all the edits I am suggesting). 

1. Include matplotlib in the installation. This is not super important since most everyone uses matplotlib, but I created a new environment and ran into errors (even when not attempting any plots). 
2. Include some of the plots in the examples. The analysis scripts automatically generate the plots, but if you are only looking at the docs, the plots would help to clarify the results.

**Comment by wehs7661** [comment]
I've opened a PR (new branch: `improve-documentation`) and left all my thoughts in the description of the PR. A lot of them are just pretty minor things but maybe there is some room for discussion. Overall, I think the documentation is very clear and beginner-friendly.

**Comment by ptmerz** [comment]
The documentation improvements, including the switch to jupyter notebooks and the improvements by @wehs7661 have taken care of most of these points, so I will close this.
