### ISSUE TITLE
Update/tweak the tutorials

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/physical_validation#64]
Located in https://github.com/shirtsgroup/physical_validation_workshop.  Place specific issues to fix that there.

**Comment by wehs7661** [comment]
I'm interested in updating the tutorials, but I will have to look into the existing ones to get a better sense of specifically what needs to be tweaked/updated.

**Comment by wehs7661** [comment]
I will work on this issue after addressing issue #49. Substantial work should be done before Feb. 15.

**Comment by wehs7661** [comment]
Sorry for getting this started late. I've just updated the README of the repo `physical_validation_workshop` in the newly created branch `tweak_tutorials` with the following changes:
- The directory structure for the folder `ensemble` was wrong, so I’ve updated it with the output of the `tree` command. I’ve updated the directory structure for `equipartition` so that the formats are consistent.
- I’ve updated the description and the sectioning a little bit so it is slightly more clear. Descriptions directing to non-existing files have also been fixed.

I've also tried running all the jupyter notebooks and Python codes. All of them worked except that line 31 in `ana.py` in folder `equipartition/trp-cage` returned an error for each `d` in the loop. Below is a part of the STDERR:
```
  File "/Users/Wei-TseHsu/Documents/Life in CU Bouler/Research in Shirts Lab/Code_development/physical_validation_workshop/equipartition/trp-cage/ana.py", line 29, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    results_protein = gmx.get_simulation_data(mdp=str(d) + '/protein.mdp',
  File "/usr/local/lib/python3.9/site-packages/physical_validation/data/gromacs_parser.py", line 136, in get_simulation_data
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
    trajectory_dict = self.__interface.read_trr(trr)
  File "/usr/local/lib/python3.9/site-packages/physical_validation/util/gromacs_interface.py", line 221, in read_trr
  File "/Users/Wei-TseHsu/Documents/Life in CU Bouler/Research in Shirts Lab/Code_development/physical_validation_workshop/equipartition/trp-cage/ana.py", line 29, in <module>
    results_protein = gmx.get_simulation_data(mdp=str(d) + '/protein.mdp',
  File "/usr/local/lib/python3.9/site-packages/physical_validation/data/gromacs_parser.py", line 136, in get_simulation_data
    os.remove(tmp_dump)
FileNotFoundError: [Errno 2] No such file or directory: 'gmxpy_protein.dump'
```
Interestingly, with exactly the same code filled in `ana.ipynb` in the same folder, `ana.ipynb` didn't return any errors. Also, right after I killed the execution of `ana.py`, `gmxpy_protein.dump` was indeed in the same folder, so I thought `os.remove('gmxpy_protein.dump')` should have been able to locate and delete the files. 

Regarding the unaddressed issues, I'm not sure if I understand the descriptions of the issue. For issue shirtsgroup/physical_validation_workshop#6, does it mean that we don't actually need to specify the paths as long as `GMXRC` is run properly? Also, for shirtsgroup/physical_validation_workshop#7, does that mean we want to break the for loops (e.g. the nested loop in shirtsgroup/physical_validation_workshop/ensemble/water/ana_gromacs.ipynb) so that the user can identify which parts of the output correspond to which test more easily? I think it would be more clear but the notebook will become more lengthy. Or maybe we can just print out the explanatory text indicating which test a certain part of the output (e.g. a figure) belongs to. What's your opinion, @mrshirts and @ptmerz ?

**Comment by ptmerz** [comment]
https://physical-validation.readthedocs.io/en/latest/index.html does now include python notebooks with outputs under `Examples`. These notebooks contain examples / tutorials for all the functionality of physical validation. They can be downloaded and run locally (see note on top of each separate notebook). It will also be easier to keep the examples up-to-date if they live in the same repo as the main code. 

I therefore think that these can be considered to supersede the examples in https://github.com/shirtsgroup/physical_validation_workshop, so I'm closing this.

If it is useful for educational purposes to have a different set of examples, we can certainly revive the repo at https://github.com/shirtsgroup/physical_validation_workshop for that purpose. Feel free to reopen this issue, or open a new one here or over at https://github.com/shirtsgroup/physical_validation_workshop to discuss this in more details if you feel it would be beneficial @mrshirts.
